allow_remote_control yes
listen_on unix:~/.cache/kitty/kitty

# Font
font_family JetBrainsMono Nerd Font
bold_italic_font auto
font_size        9.0

# Window
window_padding_width 14
hide_window_decorations yes
confirm_os_window_close 0

# Keybindings
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

# Aesthetics
cursor_shape block
cursor_trail 1
cursor_blink_interval 0

# Theme
include ~/.config/oxidize/themes/current/kitty.conf
