# Generated by oxidize — do not edit directly.
# Edit oxidize/themes/templates/helix.toml.tpl instead.

"ui.background"                    = { bg = "background" }
"ui.background.separator"          = { fg = "color8" }
"ui.text"                          = { fg = "foreground" }
"ui.text.focus"                    = { fg = "foreground", modifiers = ["bold"] }

"ui.linenr"                        = { fg = "color8" }
"ui.linenr.selected"               = { fg = "foreground", modifiers = ["bold"] }

"ui.cursor"                        = { modifiers = ["reversed"] }
"ui.cursor.primary"                = { modifiers = ["reversed"] }
"ui.cursor.secondary"              = { modifiers = ["reversed"] }
"ui.cursor.match"                  = { fg = "color11", underline = { color = "color11", style = "line" } }
"ui.cursorline.primary"            = { bg = "color8" }
"ui.cursorline.secondary"          = { bg = "color8" }

"ui.selection"                     = { bg = "color8" }
"ui.selection.primary"             = { fg = "selection_foreground", bg = "selection_background" }

"ui.statusline"                    = { fg = "foreground", bg = "color8" }
"ui.statusline.inactive"           = { fg = "color7", bg = "color8" }
"ui.statusline.normal"             = { fg = "color0", bg = "accent" }
"ui.statusline.insert"             = { fg = "color0", bg = "color10" }
"ui.statusline.select"             = { fg = "color0", bg = "color13" }
"ui.statusline.separator"          = { fg = "color8" }

"ui.popup"                         = { fg = "foreground", bg = "color8" }
"ui.popup.info"                    = { fg = "foreground", bg = "color8" }
"ui.window"                        = { fg = "color8" }
"ui.help"                          = { fg = "foreground", bg = "color8" }
"ui.menu"                          = { fg = "foreground", bg = "color8" }
"ui.menu.selected"                 = { fg = "color0", bg = "accent" }
"ui.menu.scroll"                   = { fg = "color7", bg = "color8" }

"ui.gutter"                        = { fg = "color8" }
"ui.virtual.ruler"                 = { bg = "color8" }
"ui.virtual.whitespace"            = { fg = "color8" }
"ui.virtual.indent-guide"          = { fg = "color8" }
"ui.virtual.wrap"                  = { fg = "color8" }
"ui.virtual.inlay-hint"            = { fg = "color7", bg = "color8" }
"ui.virtual.inlay-hint.parameter"  = { fg = "color7", bg = "color8" }
"ui.virtual.inlay-hint.type"       = { fg = "color7", bg = "color8" }
"ui.virtual.jump-label"            = { fg = "color12", modifiers = ["bold", "underlined"] }

# Syntax
"comment"                          = { fg = "color7", modifiers = ["italic"] }
"variable"                         = { fg = "color9" }
"variable.other.member"            = { fg = "color2" }
"constant"                         = { fg = "color9" }
"constant.numeric"                 = { fg = "color9" }
"constant.character.escape"        = { fg = "color14" }
"string"                           = { fg = "color10" }
"type"                             = { fg = "color11" }
"attribute"                        = { fg = "color11" }
"function"                         = { fg = "color12" }
"constructor"                      = { fg = "color12" }
"special"                          = { fg = "color12" }
"keyword"                          = { fg = "color13" }
"label"                            = { fg = "color13" }
"namespace"                        = { fg = "color13" }
"operator"                         = { fg = "foreground" }
"punctuation"                      = { fg = "foreground" }

# Markup
"markup.heading"                   = { fg = "color12", modifiers = ["bold"] }
"markup.list"                      = { fg = "color9" }
"markup.bold"                      = { fg = "color11", modifiers = ["bold"] }
"markup.italic"                    = { fg = "color13", modifiers = ["italic"] }
"markup.strikethrough"             = { modifiers = ["crossed_out"] }
"markup.link.url"                  = { fg = "color3", underline = { color = "color3", style = "line" } }
"markup.link.text"                 = { fg = "color9" }
"markup.quote"                     = { fg = "color14" }
"markup.raw"                       = { fg = "color2" }

# Diff
"diff.plus"                        = { fg = "color10" }
"diff.minus"                       = { fg = "color1" }
"diff.delta"                       = { fg = "color12" }
"diff.delta.moved"                 = { fg = "color4" }

# Diagnostics
"warning"                          = { fg = "color11" }
"error"                            = { fg = "color9" }
"info"                             = { fg = "color12" }
"hint"                             = { fg = "color7" }
"diagnostic.warning"               = { underline = { color = "color11", style = "curl" } }
"diagnostic.error"                 = { underline = { color = "color9", style = "curl" } }
"diagnostic.info"                  = { underline = { color = "color12", style = "dotted" } }
"diagnostic.hint"                  = { underline = { color = "color7", style = "double_line" } }

[palette]
background         = "{{ background }}"
foreground         = "{{ foreground }}"
accent             = "{{ accent }}"
selection_foreground = "{{ selection_foreground }}"
selection_background = "{{ selection_background }}"
color0             = "{{ color0 }}"
color1             = "{{ color1 }}"
color2             = "{{ color2 }}"
color3             = "{{ color3 }}"
color4             = "{{ color4 }}"
color5             = "{{ color5 }}"
color6             = "{{ color6 }}"
color7             = "{{ color7 }}"
color8             = "{{ color8 }}"
color9             = "{{ color9 }}"
color10            = "{{ color10 }}"
color11            = "{{ color11 }}"
color12            = "{{ color12 }}"
color13            = "{{ color13 }}"
color14            = "{{ color14 }}"
color15            = "{{ color15 }}"
