general {
    lock_cmd = hyprlock
    before_sleep_cmd = loginctl lock-session
    inhibit_sleep = 3
}

listener {
    timeout = 300                                              # 5min: dim keyboard
    on-timeout = brightnessctl -sd '*::kbd_backlight' set 0
    on-resume = brightnessctl -rd '*::kbd_backlight'
}

listener {
    timeout = 540                                              # 9min: warn before lock
    on-timeout = notify-send "Lockscreen" "Locking in 1 minute"
}

listener {
    timeout = 600                                              # 10min: lock
    on-timeout = loginctl lock-session
}

listener {
    timeout = 660                                              # 11min: dim display
    on-timeout = brightnessctl -sd '*::backlight' set 1
    on-resume = brightnessctl -rd '*::backlight'
}

listener {
    timeout = 1200                                             # 20min: suspend
    on-timeout = systemctl suspend
}
