source = ~/.config/mango/conf.d/windows.conf
source = ~/.config/mango/conf.d/settings.conf
source = ~/.config/mango/conf.d/input.conf
source = ~/.config/mango/conf.d/binds.conf
source = ~/.config/oxidize/themes/current/mango.conf
exec-once=~/.config/mango/autostart.sh
