shadowscolor = 0x2d353bff
rootcolor = 0x2d353bff
bordercolor = 0xd3c6aaff
focuscolor = 0x7fbbb3ff
maximizescreencolor = 0xd3c6aaff
urgentcolor = 0xa7c080ff
scratchpadcolor = 0xd699b6ff
globalcolor = 0xd3c6aaff
overlaycolor = 0xd3c6aaff
